### ISSUE TITLE
How to check if python-Levenshtein is being used?

### ISSUE THREAD

**Issue by vgoklani** [seatgeek/fuzzywuzzy#103]
Hey,

Thanks for creating this library! Just a quick question, how do we check if python-Levenshtein is being used? 

Thanks!

**Comment by josegonzalez** [comment]
If it doesn't show a warning on import, it's being used.

**Comment by vgoklani** [comment]
that's a really unsatisfying answer...

**Comment by josegonzalez** [comment]
When you import the `fuzzywuzzy` library, we try to import `python-Levenshtein` by default, as specified [here](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/fuzz.py#L30). If the import fails, we fallback to using a the pure-python `SequenceMatcher` library contained in this package, and also call `warnings.warn` to notify you that the pure python version is being used.

Is that a more satisfying answer? Not sure what else you are looking for, but feel free to let me know what you're looking for.

**Comment by medecau** [comment]
It is also possible to test this by comparing difflib.SequenceMatcher to fuzz.SequenceMatcher.
It will be different when Levenshtein is used.

**Comment by josegonzalez** [comment]
@medecau good catch. In some instances it seems as though the pure python version is "better" than the compiled version. I suspect this may have to do with the underlying implementation of one or both being incorrect - or perhaps the libraries linked for the compiled version being funky. Would be nice to be able to switch between the two, adapter-style, in the future.

I think I can close this as we've provided two methods of checking.

**Comment by vgoklani** [comment]
sounds good, thanks!
