### ISSUE TITLE
Will fuzzywuzzy help sentence matching within an article?

### ISSUE THREAD

**Issue by BarryKeCMU** [seatgeek/fuzzywuzzy#111]
Hello guys,

I asked Jose this question, and he suggested me to open an issue here so you guys can see it.

Right now I am working on a Question&Answering program in Python. 

For instance, assume the question asked is "Is Michael working at New York City?" 
What I plan to do here is to find an answer to this question by going through an article sentence by sentence. It means that I am supposed to find a sentence like "Michael is currently working at New York City" and eventually give an answer of "Yes." 

In order to locate this target sentence in the article, I am planning to use "fuzz.partial_ratio" function on each sentence in the article, filter out those with low scores and keep those with high scores, and do some other analysis (I'm not done this part yet) among these high-scored sentences and eventually produce the target sentence. 

Do you guys think "fuzz.partial_ratio" is the right method for me to use?  I've tried other methods and they do not perform as accurately as "fuzz.partial_ratio".

Thank you very much!

**Comment by rishirajsurti** [comment]
If fuzz.partial_ratio gives more accurate results, it's fine. Have you tried something on the lines of Natural Language Processing? Please have a look at this [Natural Language Toolkit](http://www.nltk.org/).
