### ISSUE TITLE
StringMatcher incompatible license

### ISSUE THREAD

**Issue by rjframe** [seatgeek/fuzzywuzzy#113]
StringMatcher.py was virtually lifted from [the upstream source](https://github.com/miohtama/python-Levenshtein/blob/master/StringMatcher.py), which is [GPL2](https://github.com/miohtama/python-Levenshtein/blob/master/COPYING) and cannot be re-licensed as MIT without permission of the copyright holder.

**Comment by josegonzalez** [comment]
I think we can just add the license for GPL2 as another section of our own license (and state where that license applies)?

> You may copy and distribute verbatim copies of the Program's
source code as you receive it, in any medium, provided that you
conspicuously and appropriately publish on each copy an appropriate
copyright notice and disclaimer of warranty; keep intact all the
notices that refer to this License and to the absence of any warranty;
and give any other recipients of the Program a copy of this License
along with the Program.

Does that seem like a reasonable thing to do? IANAL.

**Comment by rjframe** [comment]
My interpretation of GPL terms 0 and 2 say no... if I understand it, the entire project needs to be GPL or the file should be removed and everybody has to obtain it separately. Ick.

I would not be the best person to answer the question though.

**Comment by garetht** [comment]
The X11 license is [compatible with](http://www.gnu.org/licenses/license-list.en.html#X11License) the GPL license.

**Comment by rjframe** [comment]
@garetht OK, but StringMatcher.py needs to be listed as GPL before this is closed. It cannot be relicensed except by the copyright holder.
