### ISSUE TITLE
docs: difflib and python-Levenshtein

### ISSUE THREAD

**Issue by kiproping** [seatgeek/fuzzywuzzy#114]
Could you mention how to install the requirements difflib and python-Levenshtein. 
`pip install python-Levenshtein`. I am not sure how difflib is installed.

**Comment by josegonzalez** [comment]
`difflib` comes with python.

**Comment by deerdear** [comment]
Do I have to do something for the speedup once I've installed python-levenshtein?

Slightly OT: it was a bit messy to install python-levenshtein with anaconda. Maybe a note should be made about this in the readme? I don't know how common it is, maybe just me...

**Comment by josegonzalez** [comment]
I've never used anaconda, and I don't plan to start. If you'd like to add a section specific to anaconda to our readme, that would be cool, otherwise I don't see myself doing that. Sorry.
