### ISSUE TITLE
extractOne is not giving the best result

### ISSUE THREAD

**Issue by Phyks** [seatgeek/fuzzywuzzy#122]
Hi,

It seems that `extractOne` is giving weird results some times.

See this list of items:
```
$ cat /tmp/songs
/music/library/good/System of a Down/2005 - Hypnotize/01 - Attack.mp3
/music/library/good/System of a Down/2005 - Hypnotize/12 - Soldier Side.mp3
/music/library/good/System of a Down/2005 - Hypnotize/10 - She's Like Heroin.mp3
/music/library/good/System of a Down/2005 - Hypnotize/07 - U-Fig.mp3
/music/library/good/System of a Down/2005 - Hypnotize/03 - Kill Rock 'n Roll.mp3
/music/library/good/System of a Down/2005 - Hypnotize/11 - Lonely Day.mp3
/music/library/good/System of a Down/2005 - Hypnotize/02 - Dreaming.mp3
/music/library/good/System of a Down/2005 - Hypnotize/06 - Tentative.mp3
/music/library/good/System of a Down/2005 - Hypnotize/08 - Holy Mountains.mp3
/music/library/good/System of a Down/2005 - Hypnotize/09 - Vicinity of Obscenity.mp3
```

and this query:
```
>>> from fuzzywuzzy import process
>>> songs = [i.strip() for i in open("/tmp/songs").readlines()]
>>> process.extractOne("System of a down - Hypnotize - Heroin", songs)
('/music/library/good/System of a Down/2005 - Hypnotize/01 - Attack.mp3', 86)
```

Not sure how it could be enhanced, but I would have expected it to give
```
/music/library/good/System of a Down/2005 - Hypnotize/10 - She's Like Heroin.mp3
```

Thanks

**Comment by Mikadily** [comment]
I ran in to similar problem and have been able to solve it by adding different scorer funcion:

`
>>> process.extractOne("System of a down - Hypnotize - Heroin", songs)
('/music/library/good/System of a Down/2005 - Hypnotize/01 - Attack.mp3', 86)
>>> process.extractOne("System of a down - Hypnotize - Heroin", songs, scorer=fuzz.token_sort_ratio)
("/music/library/good/System of a Down/2005 - Hypnotize/10 - She's Like Heroin.mp3", 61)
`

**Comment by Phyks** [comment]
@Mikadily Thanks for the tip!

@josegonzalez Maybe it could be worth adding a note about this in the README?

**Comment by josegonzalez** [comment]
@Phyks mind sending me a pull request with the doc changes?

**Comment by Phyks** [comment]
[Here](https://github.com/seatgeek/fuzzywuzzy/pull/132) is such a PR :) Thanks
