### ISSUE TITLE
difflib and levenshtein exchangeability?

### ISSUE THREAD

**Issue by josepablog** [seatgeek/fuzzywuzzy#126]
I'm trying to decide whether to use difflib or fuzzywuzzy in my project.

I understand that difflib does NOT use minimal edit distance, but fuzzywuzzy does (thru the levenshtein library).  So, both libraries would return different results. Is this correct? I'm confused how both libraries differ.

Thank you for the great library, btw.

**Comment by josegonzalez** [comment]
We use the `SequenceMatcher` module from the difflib package to provide the functionality we need for string comparison. If python-levenshtein is installed, we will use that instead (because it is faster).

**Comment by josepablog** [comment]
Thank you for your reply.

So, if python-levenshtein is installed, the results will be different?

**Comment by josegonzalez** [comment]
If anything, the differences will be minimal (we've tested it in production with and without the extra package) though significantly sped up.

**Comment by josepablog** [comment]
`SequenceMatcher` [reportedly](https://docs.python.org/2/library/difflib.html) does not use Levenshtein distance ...

**Comment by josegonzalez** [comment]
Relevant import is here, which may help explain what exactly we are doing: https://github.com/seatgeek/fuzzywuzzy/blob/56bc3d06336e6842a9f3f06e57e4af18db5175bf/fuzzywuzzy/fuzz.py#L31

The [StringMatcher](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/StringMatcher.py) module roughly correlates to SequenceMatcher from difflib.
