### ISSUE TITLE
more details on token set ratio?

### ISSUE THREAD

**Issue by randomgambit** [seatgeek/fuzzywuzzy#127]
Hello everyone,

Thanks for this amazing package that I regularly put to the test using 10GB+ large datasets of strings.

I would like to know if someone could give me the exact computation (or just more details) used to get the token set ratio. 

I see here http://chairnerd.seatgeek.com/fuzzywuzzy-fuzzy-string-matching-in-python/ that the scores increase when (a) that makes up a larger percentage of the full string, and (b) the string remainders are more similar.

But as I am doing academic research, I need to know what's going on. Could you please give me more details?

Besides, by looking at the code, I see that there are two different token set functions

```
def token_set_ratio(s1, s2, force_ascii=True, full_process=True):
    return _token_set(s1, s2, partial=False, force_ascii=force_ascii, full_process=full_process)


def partial_token_set_ratio(s1, s2, force_ascii=True, full_process=True):
    return _token_set(s1, s2, partial=True, force_ascii=force_ascii, full_process=full_process)
```

what is the purpose of `partial_token_set_ratio`? By looking at the code, I am unsure and there is nothing about it in the docs.

many thanks!

**Comment by josegonzalez** [comment]
@acslater00 mind filling in some details here? I can add docs if you can clarify the above.

**Comment by randomgambit** [comment]
thanks guys!

I am matching sentences like

`the guys that developed fuzzywuzzy are super responsive`

`update: the guys that developed fuzzywuzzy are super responsive 2016`

where I care a bit more about the common value of these long sentences. `token_set_ratio` seems to work well but I need to understand what is going on and whether `partial_token_set_ratio` (not documented) is actually more appropriate.

Thanks!

**Comment by randomgambit** [comment]
hello everybody! sorry to bump the thread but do you have some time to help me out? After all, it is important to understand which formula is being used in your great program

thanks!

**Comment by josegonzalez** [comment]
It uses `partial_ratio` as the ratio function which uses the best partial match from a set of matching blocks. The `ratio` ratio function matches on the entire input.

The `partial_ratio` function may give better results but it can invoke the SequenceMatcher quite a bit more depending upon the number of matching blocks that were generated.

**Comment by rahul-nath** [comment]
The ratio is performed on the token set that is partitioned into three parts using both directions of set difference and the intersection of the two sets. 

Three ratios are taken: the intersection over the two set differences, and the ratio of the set differences together. 

The largest of those ratios is returned as the token_set ratio. Hope that helps a little more.
