### ISSUE TITLE
Incompatible License

### ISSUE THREAD

**Issue by michaelmovies** [seatgeek/fuzzywuzzy#130]
I see you've got issue #113 closed, however a simple reading of the GPL linked in the StringMatcher file doesn't just imply, but in fact definitively states, that your project *must* be licensed as GPL.

> **1**. You may copy and distribute **verbatim copies of the Program's
>source code** as you receive it, in any medium, provided that you
>conspicuously and appropriately publish on each copy an appropriate
>copyright notice and disclaimer of warranty; keep intact all the
>notices that refer to this License and to the absence of any warranty;
>and give any other recipients of the Program a copy of this License
>along with the Program.

You have not copied the entire source verbatim, you've copied a select portion and incorporated it into a further derived work.

> **2.** You may modify your **copy or copies of the Program or any portion**
>of it, **thus forming a work based on the Program**, and copy and
>distribute such modifications or work under the terms of Section 1
>above, provided that you also meet all of these conditions:
>
>    a) You must cause the modified files to carry prominent notices
>    stating that you changed the files and the date of any change.
>
>    b) **You must cause any work that you distribute or publish, that in
>    whole or in part contains or is derived from the Program or any
>    part thereof, to be licensed as a whole at no charge to all third
>    parties under the terms of this License**.

Emphasis added. When you decided to copy in a portion of the code from python-levenshtein you incidentally selected the GPL license for your project, and it's been apparently licensed as MIT / X11, but effectively and legally licensed as GPL, ever since.

I say this as someone who has a company project that's now been copy-lefted by your code, albeit accidentally and inadvertently.

**Comment by kevin-brown** [comment]
I'm going to add to this some more, replying to [this comment in the other ticket](https://github.com/seatgeek/fuzzywuzzy/issues/113#issuecomment-203481552):

> The X11 license is compatible with the GPL.

The X11 license is compatible with the GPL version 3 (GPLv3) license. This means that code licensed under the X11 license can be used with code licensed under the GPLv3 license, and still remain GPLv3 compatible. This does not necessarily mean it remains X11 compatible.

StringMatcher, and the python-Levenshtein library, are [licensed under GPL Version 2](https://github.com/miohtama/python-Levenshtein/blob/1a467677ff6c3faedbb5c3960877e25dcb1b8ab3/COPYING). The GPLv2 license is also compatible with the X11 license, but it is only one-way compatible. This means that your X11 licensed code can be used in a GPLv2 project, but some project's GPLv2 licensed code cannot be used in your X11 project.

http://choosealicense.com/licenses/gpl-2.0/
http://choosealicense.com/licenses/mit/

_Since I mentioned one of their comments... /cc @garetht_

**Comment by garetht** [comment]
I agree now that the project in its current form is incompatible with the license we have selected. We should be able to avoid triggering section 2b by including a completely unaltered copy of source of `python-levenshtein`, unless no one (@acslater00)  objects to moving the project to GPLv2.

**Comment by michaelmovies** [comment]
Afraid not, on including a completely unaltered copy; you've already incorporated a portion (or the whole) of the original work into your work. That mean it's been a derived work -- and therefore must be licensed under GPL 2.0 -- from the moment the file was copied and committed to Github (and therefore transmitted).

Section 1 allows you to transmit a complete, unaltered copy of the entire source (which in this case would mean the entire P-L repo), so long as it carries the license file, etc., but as soon as you modify that copy (by for instance cherry-picking just one file), or use the project, in whole or in part, in another work, then you've tripped the copyleft clause in section 2.

Unfortunately (or fortunately if you're a proponent of copyleft) there's really no wiggle room with GPL; use even a line copied from within a GPL licensed work and you're bound to release under GPL ... use the whole thing and you definitely are. Stallman and Gnu have forcefully argued that even just having "uses readline if available" type functionality triggers the clause, and you've incorporated an actual file into your own work.

Sorry, not sure your stance on CL, and not sure what sort of impact this might have downstream, but it's pretty clear that you've got to re-license as GPL2.

M

**Comment by garetht** [comment]
Without reference to your other points it seems essentially right in this case that with the current status of this project the license should be GPLv2.

https://github.com/seatgeek/fuzzywuzzy/pull/131

**Comment by michaelmovies** [comment]
Great; would maybe add that to the "CHANGES.rst" as it's non-trivial.

**Comment by josegonzalez** [comment]
When I make a release I will.

**Comment by graingert** [comment]
@yawpitch

> When you decided to copy in a portion of the code from python-levenshtein you incidentally selected the GPL license for your project

This is not correct, including GPL software doesn't make your software magically GPLed.

**Comment by yawpitch** [comment]
Please explain your reasoning, don't just make an assertion.

>>> 0. This License applies to any program or other work which contains
a notice placed by the copyright holder saying it may be distributed
under the terms of this General Public License. The "Program", below,
refers to any such program or work, and a "work based on the Program"
means either the Program or any derivative work under copyright law:
that is to say, a work containing the Program or a portion of it,
either verbatim or with modifications and/or translated into another
language.

That is pretty clear; this project has copied a portion of someone else's copyrighted work, a work released under the GPL, which is a strong copyleft license... this project is, reasonably and I think obviously, "work based on the Program". Unless an argument can be made that the fuzzywuzzy is not a derivative work (which would be hard, since it incorporated a direct copy of the GPL source in its own body), fuzzywuzzy is GPL'd, or at least must be released under a GPL compatible license. No magic is involved, that's what the GPL is designed to do.

Now, I'm not a lawyer, but I've worked for a large number of lawyers who have said that's exactly how it works... but they may very well be wrong, I just would like an explanation as to why it is wrong, preferably with some citations.

Thanks,

Michael

**Comment by graingert** [comment]
> must be released under a GPL compatible license

That doesn't apply retroactively

**Comment by yawpitch** [comment]
How is it being applied retroactively?

Any versions of fuzzywuzzy released before incorporating the GPL code were released under whatever license the creator wished. Any versions released that incorporate the GPL code must themselves be GPL. If the GPL code is removed, any further releases can revert to the original license, or choose another non-GPL license. Nothing is happening in a retroactive manner.

Sorry if I'm misunderstanding, but if I'm not then you are saying that one can trivially avoid the copyleft provisions of the GPL (and by extension also release say Microsoft's code in your project) merely by having made a prior release of an empty file under the license of your choosing.

**Comment by graingert** [comment]
> Any versions of fuzzywuzzy released before incorporating the GPL code were released under whatever license the creator wished

Correct

> Any versions released that incorporate the GPL code must themselves be GPL

Not correct. SeatGeek are just not complying with the GPL. Currently fuzzywuzzy has not applied the GPL license and is just in violation of the GPL.

**Comment by josegonzalez** [comment]
Wait, how are we in violation at the moment? We've relicensed the entire thing as GPLv2.

**Comment by graingert** [comment]
@josegonzalez where, I don't see it.

**Comment by josegonzalez** [comment]
https://github.com/seatgeek/fuzzywuzzy/blob/master/LICENSE.txt

**Comment by josegonzalez** [comment]
Lord have mercy:

> Why license notices?
> The purpose of a free software license is to give certain rights to all users of a program. If it is not clear what rights you have given them, that defeats the purpose. Our practices are designed to avoid any uncertainty.
> 
> If a program has a copy of a license FOO alongside the source files, but doesn't have an explicit statement that “This program is released under license FOO,” that leaves room for uncertainty about whether the license FOO applies to the code of that program.
> 
> If a release has one statement that “This program is released under license FOO,” in a central place such as the README file, that makes the situation clear for that release. However, programmers often copy source files from one free program into another. If a source file contains no statement about what its license is, then moving it into another context eliminates all trace of that point. This invites confusion and error.

https://www.gnu.org/licenses/gpl-howto.en.html

I'll attach the license to each python file in this repository - I think that is enough, as it seems absurd to me that our `tox.ini` or the `MANIFEST.in` would need it - in a bit. Is that enough to satisfy the GPLv2 requirement?

**Comment by yawpitch** [comment]
You're not in violation of anything, you already corrected the breach.

When I originally pointed out that you'd "effectively" licensed as GPL you responded correctly, because you had. When you're in breach of GPL your code that is in breach can pretty safely be used by anyone (provided they release GPL) because your incompatible license was (again effectively) rendered null and void the moment you incorporated GPL code.

He's right that you could have simply sat there in breach and refused to fix it, but that wouldn't have much force in court if you ever tried to stop someone else from using and releasing your code under GPL.

M

**Comment by graingert** [comment]
> your incompatible license was (again effectively) rendered null and void the moment you incorporated GPL code.

false

**Comment by graingert** [comment]
@josegonzalez I've included the notice here: https://github.com/graingert/fuzzywuzzymit/commit/1d55a6f03883ad3b938553e0ab2e12816bebb3dd

**Comment by yawpitch** [comment]
Don't worry about it, he's being trolling and pedantic.

The license is already incorporated and applied; it happened automatically when you incorporated the GPL code (look for the clause that says that an automatic license is transferred with the code, and in any program using the code). You should really have a copyright statement at the top of some file or in the README stating that it's in use, but it's already in use.

**Comment by graingert** [comment]
People think the GPL is a lot more vial than it actual is. This is an error. the GPL can only compel you to do things already required by copyright law.

**Comment by josegonzalez** [comment]
Regarding adding a license notice, from the GPLv2 source:

> To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
convey the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

Note it says "safest" there. There is ambiguity in how we can choose to apply the license. In this case, we are distributing the project via Github, which has multiple ways of pointing out the license. If a user chooses to copy a file out and disregard the license, they can do so quite easily and strip the license. We're also highly unlikely to go after anyone choosing to do so, and therefore I think we are okay to continue along our path (IANAL and don't take what I'm saying as anything coming from a lawyer).

I've already spent my entire morning thinking about this issue and I believe we are in compliance. The entire project is currently under GPLv2. I believe that information is already prominently displayed. We are currently uninterested in relicensing the project.

**Comment by graingert** [comment]
> The entire project is currently under GPLv2. I believe that information is already prominently displayed.

Where?

**Comment by josegonzalez** [comment]
In the header on the github landing page: https://cl.ly/3u2M2N1x0Y0x
As well as in the file named LICENSE.txt: https://cl.ly/311r12362V0x

Seems as though GPLv2 would prefer a `COPYING` file, but [github doesn't support autodetecting that](https://help.github.com/articles/licensing-a-repository/), so the current naming method is better.

**Comment by yawpitch** [comment]
All you really might want to do is add a COPYING file indicating that the program is released under the license found in the accompanying LICENSE file, and that's if you want to be particularly careful.

The whole reason this issue was ever brought up by me was that I was tasked with finding something like fuzzywuzzy that did not incorporate GPL code because some very highly paid and experienced lawyers were under the opinion that it works in a manner inconsistent with what's being said above; ie that your project was de facto (and in their mind de jure) licensed under GPL, whether or not you chose to agree with their interpretation.

I also am not a lawyer, but as I understand it you cannot re-license as dual in any case ... MIT code cannot incorporate GPL code and remain MIT licensed. GPL code can incorporate MIT. It's not a bi-directional compatibility.

M

**Comment by graingert** [comment]
But the license.txt literally says how to apply it, and that hasn't been
done.

**Comment by josegonzalez** [comment]
@yawpitch thank you for your comment. Basically I can add the following statement to `COPYING`?

```
    Copyright (C) 2011 Adam Cohen

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111 USA
```

Right @yawpitch ?

**Comment by graingert** [comment]
@josegonzalez you should also consider a CLA

**Comment by graingert** [comment]
I found `pylev`

**Comment by graingert** [comment]
Also https://github.com/aflc/editdistance/blob/master/README.rst

**Comment by yawpitch** [comment]
That should be sufficient for all but the most lawyery of lawyers.

Stallman would probably say you should:

1. Change LICENSE to COPYING.
2. Incorporate that text you've proposed for COPYING below into the top section of every file.

But the practical reality is that should anyone ever want to sue on this issue, it's your intent that matters more than anything else. You've established sufficiently to all but the most nitpicky that your intent was and is to release under GPL 2.0 by incorporating the LICENSE file in your code (as that's the established practice of probably at least half of Github users, and IIRC what their "use this license" feature adds to your repo for you. Anyone else should do their due diligence, see the GPL incorporated, and know that they're GPL-tainted (if that matters to them, it probably shouldn't) regardless of how strictly you follow the letter of the FSF recommendations.

As for other projects for Lev-distance, yes there was pylev, though at the time I tried it it wasn't as fast. In the end it got mooted, as the feature request went away and we never ended up needing it anyway.

I'm sorry this has been drawn out like this; from my perspective you'd done more than enough to make your intent clear by incorporating the LICENSE file.

M

**Comment by yawpitch** [comment]
BTW, one, fairly well-reasoned opinion on CLAs, and the lack of need thereof.

https://sfconservancy.org/blog/2014/jun/09/do-not-need-cla/

And a counterpoint:

https://julien.ponge.org/blog/in-defense-of-contributor-license-agreements/

As the idea has somewhat died off (full disclosure, personally tend to agree with the top).

M

**Comment by yawpitch** [comment]
No problem at all, and if I'm ever in New York I'll try and take you up on that. It might be after 2020, though.

One change that might be helpful is specifying in setup.py that it's GPLV2 specifically, as right now it just says GPL, which is somewhat ambiguous on pypi. You might also add the license to the "classifiers" section, where I believe the official string should be "License :: OSI Approved :: GNU General Public License v2 (GPLv2)".

Honestly those are niceties, but at least you're doing a favor to anyone searching via PyPi.

Cheers,

M
