### ISSUE TITLE
Swift port

### ISSUE THREAD

**Issue by lxian** [seatgeek/fuzzywuzzy#133]
Hi,
I am currently working on porting this awesome fuzzy string matching library to Swift. It's pretty much done and you can find it here. [Fuzzywuzzy_swift](https://github.com/lxian/Fuzzywuzzy_swift)

I got one question about the python implementation though. In the function `WRatio`(`fuzz.py`), there are some numbers like

```
unbase_scale = .95
partial_scale = .90
if len_ratio < 1.5:
if len_ratio > 8:
        partial_scale = .6
```

I'm a bit curious about them. Is there any chance that I can get more information about those numbers? I'm currently working on that part.

Thanks a lot !

**Comment by josegonzalez** [comment]
@acslater00 ^ do you recall why you chose those constants?

**Comment by acslater00** [comment]
They worked well for the seatgeek use case at the time, so they were
definitely pretty arbitrary.

**Comment by josegonzalez** [comment]
There you have it :)
