### ISSUE TITLE
Document method to disable "Install python-Levenshtein" warning

### ISSUE THREAD

**Issue by jdtoy** [seatgeek/fuzzywuzzy#154]
I'm using FuzzyWuzzy on Google App Engine.

To achieve scale, GAE's Standard Environment restricts low level C implementations. As such, python-Levenshtein cannot be used, but the log files warn:
> UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning

From: [fuzzywuzzy/fuzz.py#L33](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/fuzz.py#L33)

These are generated every time the application is instantiated and, in this case, are unresolvable because python-Levenshtein builds on Levenshtein.c.

@josegonzalez Has previously covered the reasoning for the logging behaviour in:
[67: UserWarning: Using slow pure-python SequenceMatcher](https://github.com/seatgeek/fuzzywuzzy/issues/67), and
[100: Unnecessary warning should be removed](https://github.com/seatgeek/fuzzywuzzy/issues/100). In both cases the resolution was "install python-Levenshtein".

Please consider:

- removing the unnecessary warning, or
- downgrading the warning to debug level, or
- providing a method for disabling the warning in the docs.

Regardless of outcome can I note that there is a need/use for a great pure-python fuzzy matching library (Go FuzzyWuzzy!), and therefore python-Levenshtein should always be an option? (Rather than a requirement, as suggested in #67.)

**Comment by josegonzalez** [comment]
There is a note in the requirements as the need for this dependency and a link to an issue as appropriate. If you feel that is not enough, please make a pull request to expand that section.

I will not be removing the warning.

**Comment by cdimitroulas** [comment]
can we at least have an option to silence the warning?

**Comment by josegonzalez** [comment]
This is apparently how you can silence warnings in your codebase: https://stackoverflow.com/a/14463362/1515875

**Comment by cdimitroulas** [comment]
thanks, appreciate the guidance
