### ISSUE TITLE
pip - fuzzywuzzy does not provide the extra 'speedup'

### ISSUE THREAD

**Issue by dnlcrl** [seatgeek/fuzzywuzzy#158]
Hi, 
I just want to note that the command:

`pip install fuzzywuzzy[speedup]`

doesn't install `python-Levenshtein`, pip (v8.1.1) actually it says `fuzzywuzzy 0.14.0 does not provide the extra 'speedup'`, so one must run `pip install python-Levenshtein` to get `python-Levenshtein` working and removing the related warning.

Thank you for this great package!

**Comment by josegonzalez** [comment]
Should be fixed as of `0.15.0`, which I just released.
