### ISSUE TITLE
Logger causes None to be returned when query is unicode and gets collapsed down to nothing

### ISSUE THREAD

**Issue by ajefferiss** [seatgeek/fuzzywuzzy#159]
Within process.py the call to logging.warning will cause a exception to be raised, and result in None being returned if the query gets collapsed down to a empty unicode string.

The call on line 105 of process.py should be:
```
logging.warning(u"Applied processor reduces input query to empty string, "
                        "all comparisons will have score 0. "
                        "[Query: \'{0}\']".format(query))
```

**Comment by ajefferiss** [comment]
I've created a pull request for the change. https://github.com/seatgeek/fuzzywuzzy/pull/160

**Comment by josegonzalez** [comment]
Closing as the pull request was merged.
