### ISSUE TITLE
fuzzywuzzy doesn't find python-Levenshtein module in python3.6

### ISSUE THREAD

**Issue by shrx** [seatgeek/fuzzywuzzy#166]
I have this problem wih fuzzywuzzy in python 3.6:

```
python3.6 -c "import sys; print(sys.version); import fuzzywuzzy.fuzz"
3.6.1 (default, Mar 22 2017, 06:17:05) 
[GCC 6.3.0 20170321]
/usr/local/lib/python3.5/dist-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
```

But not in 3.5:

```
python3.5 -c "import sys; print(sys.version); import fuzzywuzzy.fuzz"
3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
```

**Comment by josegonzalez** [comment]
What happens when you run the following code in your python cli?

```
from __future__ import unicode_literals
import platform
import warnings

try:
    from .StringMatcher import StringMatcher as SequenceMatcher
except ImportError:
    if platform.python_implementation() != "PyPy":
        warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
```

**Comment by shrx** [comment]
I get this warning:
```
__main__:5: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
```

**Comment by josegonzalez** [comment]
Sounds like you don't have python-Levenshtein installed then, as thats exactly the code we check to verify that we can import it. Please ensure you have the correct dependencies in your 3.6 installation.

**Comment by wielrenner** [comment]
I got the same. Don't know what's going on. 

python                             3.6.6                      hea74fb7_0
python-Levenshtein        0.12.0                    <pip>

When running
`from Levenshtein import *`
I get
`File "C:\Users\WoutervanRoosmalen\Anaconda3\lib\site-packages\Levenshtein\__init__.py", line 1, in <module>
    from Levenshtein import _levenshtein
ImportError: cannot import name '_levenshtein'`
