### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by cgivre** [seatgeek/fuzzywuzzy#170]
Hello there, 
First of all, I want to thank you for this awesome library.   I used it for a project recently and was really impressed.  Anyway, I wrote a collection of functions for Apache Drill which include a wrapper for the Java version of your library (https://github.com/cgivre/drill-phonetic-functions).   I'd like to submit this for inclusion in Apache Drill, however, since your library is licensed under GPL and the GPL license is not compatible with the Apache license, I can't. 
I wanted to ask if you would consider releasing this under a license, such as BSD or Apache so that it could be included in the next version of Drill?  (https://www.apache.org/legal/resolved.html) 
Thank you and keep up the good work!

**Comment by josegonzalez** [comment]
We originally licensed it as MIT, but originally pulled in some code that was GPL, so the whole thing turned to GPL without us knowing, as shown in #130.

Thankfully the GPL is a viral license so we can't just relicense it as we would prefer, and instead anything that uses this in a distribution must also be GPL. Go Stallman!

I truly wish I could relicense it to BSD or similar, but it is what it is. :(.

**Comment by graingert** [comment]
@cgivre  

I've created fuzzywuzzymit, a fork without any GPL code in: https://pypi.python.org/pypi/fuzzywuzzymit

I've also made a PR to use this upstream package in fuzzywuzzy and apply the GPL code to it: https://github.com/seatgeek/fuzzywuzzy/pull/199

**Comment by josegonzalez** [comment]
The mentioned PR may not be wholly legal from a licensing perspective, so I would hesitate to use the fork before we get that sorted. Thanks.
