### ISSUE TITLE
Question: Can library be used across dataset without a matching variable

### ISSUE THREAD

**Issue by Austin1** [seatgeek/fuzzywuzzy#177]
That subject probably doesn't make sense because I don't know the most appropriate way to articulate my question.

If I have a data set that has a column of thousands of records where some values would fuzzy match each other and others wouldn't, could I find a way to "group" the matches together?

For example:

ID | Name
1 McDonalds Corp
2 McDonald's Corporation
3 Burger King
4 Burger King Corp.
5 Burger King Corporation
6 ...

Let's assume you've got something like this but with 30,000 records and many "distinct" fuzzy matches (above example has 2 distinct fuzzy matches).

Is there a way to ID all the fuzzy matches across the entire data set so that I can correlate ID's 1,2 and 3,4,5?

**Comment by josegonzalez** [comment]
My naive approach would be to match each one of those to each other thing in the set. You can do that via `process.extract()` [like so](https://github.com/seatgeek/fuzzywuzzy#process).
