### ISSUE TITLE
suspicious statement "block[1] - block[0]" in partial_ratio

### ISSUE THREAD

**Issue by lihebi** [seatgeek/fuzzywuzzy#207]
Hi,

I noticed [this line](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/fuzz.py#L57) in the function `partial_ratio` is very suspicious.

```python
long_start = block[1] - block[0] if (block[1] - block[0]) > 0 else 0
```

The matching blocks returned from `SequenceMatcher` is of the form `(a,b,size)` where `a` (`block[0]`) and `b` (`block[1]`) are the indexes in *each* of the input strings, i.e. `s1[a:a+size]` should match `s2[b:b+size]`. It makes *no sense* to me to compute `b-a`, and use it as starting index of the long string.

I noticed there are several open and closed issues about the behavior of `partial_ratio`, #193 #191, #141 #99 to name a few. This may be the reason.

**Comment by josegonzalez** [comment]
That was introduced for this issue: https://github.com/seatgeek/fuzzywuzzy/issues/7

Given that tests pass, is there something here that is broken, and can you provide a testcase to prove that? Thanks in advance :)

**Comment by lihebi** [comment]
OK I see, the purpose is to align the matched sub-string. Closing this.

**Comment by shreekarade** [comment]
can you suggest solution for this.

**Comment by shreekarade** [comment]
process.extract(q,list,scorer=fuzz.partial_ratio, limit=10)
This not working properly, not behaving properly

i am using q as long string(length 9344).
