### ISSUE TITLE
`exactractBests` returns strings that are not the "best"

### ISSUE THREAD

**Issue by TMiguelT** [seatgeek/fuzzywuzzy#215]
If I run `process.extractBests(token, choices, limit=None)`, I would expect to only get strings that have the (equal) best match score, but instead I get a list of matches of `token` with _every_ word in `choices`. 

For instance, if I run `process.extractBests('abandonned', dictionary, limit=None)`, I get:
```
('abandoned', 95)
('ab', 90)
('aba', 90)
('aband', 90)
...
```

In this case I only want the first string, `'abandoned'`, since it is the only string with the highest match score. Am I misunderstanding this function? Is there another function that does this?

**Comment by UpwardTrajectory** [comment]
`process.extractOne(query, choices, processor=default_processor, scorer=default_scorer, score_cutoff=0)` does what you're requesting.  
Alternatively, you could use the hyperparamter `limit` combined w/ some indexing to always give you the best single string:
`process.extractBests('abandonned', dictionary, limit=1)[0][0]`. (This doesn't deal w/ a "tie" though)

Semantically, I can see where "Bests" could be only the actual "Best", unless there's a tie, then give me multiple. However, in this implementation, "Bests" means the "Best k strings, sorted by score" where `limit=k`
