### ISSUE TITLE
different results with Qratio

### ISSUE THREAD

**Issue by jx57** [seatgeek/fuzzywuzzy#221]
python = 3.6
jupyter = 6.2.1

x1 = ['荣耀', '2018', '年', '上半年', '互联网', '手机', '销量', '夺冠', '目标', '要', '做到', '国内', '前', '三']
x2 = ['荣耀', '也', '获得', '了', '今年', '京东', '的', '手机', '类', '单日', '的', '销量', '冠军', '累计', '销量', '冠军', '以及', '2018', '年', '月', '单月', '整体', '手机', '市场', '销量', '份额', '第三', '众所周知', '现在', '国内', '手机', '销量', '前', '三', '席位', '几乎', '都', '被', '华为', 'OPPO', '和', 'vivo', '长期', '霸占', '而', '荣耀', '在', '很多', '销量', '榜单', '中', '都', '是', '和', '华为', '分开', '计算', '的', '不得不', '说', '定下', '这个', '目标', '还是', '非常', '勇气可嘉', '由此可见', '荣耀', '希望', '未来', '的', '目标', '是', '脱离', '互联网', '手机', '头衔', '只是', '在', '互联网', '手机', '领域', '称王称霸', '已经', '无法', '满足', '其', '增长', '目标', '了']
fuzz.QRatio(" ".join(x1)," ".join(x2))

The above command returned me 15, 19 in different jupyter notebooks. 15 is in a notebook that I have worked on for a while; 19 is in a newer script. I can reproduce 15 in the older notebook, but cannot do it elsewhere. 

Any suggestions of why? I just want to ensure a stable computation across all scripts. Thanks!

**Comment by josegonzalez** [comment]
I have no idea. We don't run our CI in jupyter notebooks. Is it possible some other library you are importing overrides some python internals?

**Comment by jx57** [comment]
Yes, that could be. I did not use this feature eventually for that project.
Sorry, I forgot to check git responses till today.
Thanks a lot! Have a great day!
