### ISSUE TITLE
Inconsistent score from fuzz.ratio() between linux and windows

### ISSUE THREAD

**Issue by joshuamin2014** [seatgeek/fuzzywuzzy#271]
Hi, I ran the following code on my windows machine and linux machine, and windows returns 44, whereas linux returns 33. Is it a known issue?

t1 = 'A L I E N S'
t2 = 'A S A L'
fuzzywuzzy.fuzz.ratio(t1, t2)

(fuzzywuzzy version 0.17.0)

**Comment by maxbachmann** [comment]
Hm for me this returns 44 on Linux aswell

**Comment by joshuamin2014** [comment]
fyi, it looks like it depends on python-Levenshtein (my colleague did an experiment, and then I followed to see the same behavior); with python-Levenshtein, it is returning 44, and 33 without it. I think this is a critical bug. Can somebody work on this?

**Comment by maxbachmann** [comment]
This is because it is using difflib when using a pure python implementation. The issue you describe can be found here: https://github.com/seatgeek/fuzzywuzzy/issues/128
or in the Readme as:
```
python-Levenshtein (optional, provides a 4-10x speedup in String Matching, though may result in differing results for certain cases)
```
So when you want one or the other behaviour you should install/not install python-Levenshtein

**Comment by joshuamin2014** [comment]
Oh, thanks for the clarification! I was testing an ML algorithm on my windows machine, and I saw different behavior when I tested on SageMaker. Mystery solved. Thanks!

**Comment by maxbachmann** [comment]
Yes I can understand why this can be confusing
