### ISSUE TITLE
How can I match same name in english and arabic?

### ISSUE THREAD

**Issue by imranbaloch** [seatgeek/fuzzywuzzy#277]
I have a requirement to check whether 2 identical names are matching or not. I need to check both Arabic and English. Will this library helps?

**Comment by acslater00** [comment]
Definitely an interesting problem. This library probably won't help you natively, but if you can figure out a way to convert arabic names into, perhaps, a phonetic string (maybe this? https://pypi.org/project/arabic-pronunciation/) and then do the same with english, you could probably compare the phonetic strings and get pretty close. Good luck!
