### ISSUE TITLE
FuzzyWuzzy Term must be changed

### ISSUE THREAD

**Issue by sangeetkhullar** [seatgeek/fuzzywuzzy#291]
Fuzzy Wuzzy“ is one such term that has a racial background. 
“Fuzzy Wuzzy” is a derogatory term for a black person, especially one with fuzzy hair.
This term was used by 19th century British colonial soldiers for the members of an East African nomadic tribe - the Hadendoa.
White settlers and military from other countries also later used the term to denote the indigenous dark skinned and curly haired population; 

Could you please find a better name for this library ?

**Comment by maxbachmann** [comment]
See https://github.com/seatgeek/fuzzywuzzy/issues/218

**Comment by josegonzalez** [comment]
Issue #218 covers this, and I've confirmed that this is being worked on.

I'll post a bit more context in that ticket.
