### ISSUE TITLE
Please rename this package to "FuzzyMatch" or similar.

### ISSUE THREAD

**Issue by edrandall** [seatgeek/fuzzywuzzy#320]
Sorry, but in the modern diversity/equality/inclusion climate we can't use this package simply because of the name.
The name "fuzzywuzzy" has unacceptable connotations far exceeding the "master / slave"  argument, it is right up there with the n* word.  Maybe it's a generational thing, younger colleagues aged under about 40 don't seem so aware of this one but the older ones amongst us would never dream of using this word and it makes us very uncomfortable.
Please could it be renamed to something descriptive without the loading, like "fuzzymatch" or something.

**Comment by maxbachmann** [comment]
Not sure when this will happen, but it appears that a rename is planed: https://github.com/seatgeek/fuzzywuzzy/issues/218

**Comment by edrandall** [comment]
Thankyou, I hope that this will be sorted out quickly and not drag on too much longer.
