### ISSUE TITLE
Symmetry and ratio calculation

### ISSUE THREAD

**Issue by ojomio** [seatgeek/fuzzywuzzy#61]
Sorry to write you again, 
but I noticed that when `ratio()` or `partial_ratio()` is called from next-level functions, eg `_token_sort` or `_token_set` it is called only as
 `ratio(a,b)`, 
while
 `max([ratio(a,b), ratio(b,a)])`
might produce a better match indeed. Consider the example
```
>>> fuzzywuzzy.fuzz.ratio('gs dfs f sg', 'gs fsfsgfs gsrg')
62
>>> fuzzywuzzy.fuzz.ratio('gs fsfsgfs gsrg', 'gs dfs f sg')
54
>>>
```
Considering, that in many functions you perform several comparisons in order to achieve the best score, should reverse check also be made when calling `ratio`or `partial_ratio`?

**Comment by medecau** [comment]
@ojomio is this still relevant?

`_token_sort` seems to be using `ratio(a, b)` still.

If no changes nor a conversation is to be had from this it might be better to close the issue.
