### ISSUE TITLE
partial_token_set_ratio returning significantly higher ratio than it should after upgrade to 0.4.0

### ISSUE THREAD

**Issue by dcousineau** [seatgeek/fuzzywuzzy#65]
After I upgraded to 0.4.0 I started getting the following oddity: (please note I get the `Using slow pure-python SequenceMatcher` warning, not sure if that has any bearing)

```python
from fuzzywuzzy import fuzz
line = "Notice of l ntention to Obtain a Compulsory License for Making and Distributing Phonorecords"
fuzz.partial_token_set_ratio(line, "Name of principal recording")  # 100
fuzz.partial_token_sort_ratio(line, "Name of principal recording")  # 52
```

When I downgrade back to 0.2 I get the following:

```python
from fuzzywuzzy import fuzz
line = "Notice of l ntention to Obtain a Compulsory License for Making and Distributing Phonorecords"
fuzz.partial_token_set_ratio(line, "Name of principal recording")  # 29
fuzz.partial_token_sort_ratio(line, "Name of principal recording")  # 52
```

**Comment by acslater00** [comment]
Yeah so "partial_token_set_ratio" is actually just a pretty shitty and useless method, the more I look at it. It'll return 100 for any strings for which the tokenization is non-disjoint, ie if it shares even a single token. 

See:

```
fuzz.partial_token_set_ratio("a b c d e f g", "a h")
> 100
```

The non-partial version makes somewhat more sense. 

```
fuzz.token_set_ratio("a b c d e f g", "a h")
>  50
```

If your problem domain considers this a reasonable outcome (there are certainly some problem domains where that would be the case) then it's appropriate to use this method, but the example above doesn't look like one. 

I think we should probably just close this.
