### ISSUE TITLE
How can i say for fuzzywuzzy about installed dependencies?

### ISSUE THREAD

**Issue by a-x-** [seatgeek/fuzzywuzzy#66]
// Excuse my beginner's English

Hi!

How can i explicitly resolve dependencies (show they for `fuzzywuzzy`)?
I have installed `python-Levenshtein` (by command `aptitude install python-Levenshtein`).
And i don't understand have i `difflib` or no.

Any way, `fuzzywuzzy` prints warning:
```
/tmp/fuzzywuzzy/fuzzywuzzy/fuzz.py:33: UserWarning: Using slow pure-python SequenceMatcher
  warnings.warn('Using slow pure-python SequenceMatcher')
```

I have been watching sources, but not figured out what happened...

### My code:
```python
#! /usr/bin/env python3

import sys
import re
sys.path.append('/tmp/fuzzywuzzy')
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

str1 = sys.argv[1]
str2 = sys.argv[2]
print(fuzz.ratio(str1, str2))
```

I run this script like this: `./fuzzy-compare-two-strings.py 123456 213456`

> n.b. i use Debian7

Sorry again and thanks!

**Comment by josegonzalez** [comment]
difflib is not the same: http://stackoverflow.com/a/6690850

I think you might have an import issue to look into.
