### ISSUE TITLE
UserWarning: Using slow pure-python SequenceMatcher

### ISSUE THREAD

**Issue by sylvia43** [seatgeek/fuzzywuzzy#67]
```
C:\Python27\lib\site-packages\fuzzywuzzy\fuzz.py:33: UserWarning: Using slow pure-python SequenceMatcher
  warnings.warn('Using slow pure-python SequenceMatcher')
```

The line of code I have for importing is `from fuzzywuzzy import fuzz`.

I'm running Python 2.7.8 on Windows 8, pip 1.5.6, and fuzzywuzzy 0.4.0.

**Comment by maksad** [comment]
:+1: thanks

**Comment by legel** [comment]
`pip install python-levenshtein`

(maybe consider making this a dependency)
