### ISSUE TITLE
Classifying transactions

### ISSUE THREAD

**Issue by sdementen** [seatgeek/fuzzywuzzy#71]
Hello,

I get bank account statements in csv with a date and description of the transaction per row. 

I have a set of properly categorised transactions (previously imported transactions) and I would like to categorise new transactions based on the existing set of transactions. I wanted to do a process.extract(new_transaction.description, [List of existing_transaction.description]) and then assign to the new transaction the category of the best matched transaction.  
How can I speed up the process of categorising N transaction based on a set of M transactions ? I think at each run for a new transaction, fuzzywuzzy must reprocess the M transactions. Can we preprocessing/compile the M transactions to speed it ? Other ideas ?

**Comment by josegonzalez** [comment]
No real ideas since we haven't bumped into this problem. If you have a PR to fix your speed issue, I'd love to have it. Closing since there isn't anything actionable here.
