### ISSUE TITLE
token_set_ratio() incorrect match

### ISSUE THREAD

**Issue by bscheibe** [seatgeek/fuzzywuzzy#73]
We've been using fuzzywuzzy quite successfully for a while but ran into this strange issue:

```
from fuzzywuzzy import fuzz
print round(fuzz.token_set_ratio("Recruiting Partner", "Tooling Planner"))
```

Returns a match  of 61.0. If someone could illuminate us to why this is (we might be missing something!) that'd be great. Starting to peer at the code now

Tried with both 0.3.1 and 0.4

Thanks

**Comment by josegonzalez** [comment]
@acslater00 any chance you might be able to explain this?

**Comment by bscheibe** [comment]
We've looked into the issue a little bit more. Seems like token_set_ratio() is token comparing (via difflib) both `combined_1to2` and `combined_2to1` even when the intersection of the original two strings is none: [View on Github](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/fuzz.py#L198)

We're not sure if this was your intent, but because of this it causes a match even when none of the words are the same. This is most likely due to a large amount of similar letters, but we didn't dive into difflib too deeply

Any ideas on if this was your intent would be great - when you get a chance

**Comment by josegonzalez** [comment]
Closing as @acslater00 provided what I believe is a satisfactory answer.
