### ISSUE TITLE
Fuzzy install via pip in Conda environment,  python-Levenshtein warning

### ISSUE THREAD

**Issue by dpcuneowcg** [seatgeek/fuzzywuzzy#75]
Hi...

I'm new to Conda, and just re-installed fuzzywuzzy using conda version of pip.
 python-Levenshtein is also install according to conda.

I'm using Python 3.3.

I'm not sure what to do about this...

Cheers !

**Comment by josegonzalez** [comment]
Whats the error you are seeing?

**Comment by dpcuneowcg** [comment]
Hi Jose thanks for responding... 

Conda list -n py33 python-levenshtein

python-levenshtein        0.12.0                    <pip>

I didn't try any other test to see if the levenshtein package is working...



from fuzzywuzzy import fuzz

C:\Users\dcuneo\AppData\Local\Continuum\Anaconda\envs\py33\lib\site-    packages\fuzzywuzzy\fuzz.py:33: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

**Comment by josegonzalez** [comment]
It doesn't sound like python-Levenshtein is in the path. Can you print out a list of modules available to you from within your package? Or tell me how you would import python-levenshtein?

**Comment by dpcuneowcg** [comment]
Yesterday was my first day using Anaconda / Conda, so I'm confused how the paths work.
I thought that my path included python-levenshtein but clearly it is not...

If you have any advice I'm all ears...otherwise I'll be researching this.

**Comment by josegonzalez** [comment]
Try http://stackoverflow.com/a/9194180

**Comment by dpcuneowcg** [comment]
Thanks...I've figured out that Conda has it's own pip which will integrate the conda and pip packages. I knew this, but I guess I didn't install pip in the "root" conda environment.

Plus i'm doing all this on Windoze for now...I think I'll get it working...thanks for your input.

Cheers

**Comment by josegonzalez** [comment]
Let me know how it should work so we can update docs or update the package :)

**Comment by josegonzalez** [comment]
@dpcuneowcg Any luck?

**Comment by dpcuneowcg** [comment]
?yes, sorry I didn't get back to you.


It was a matter of learning the Anaconda/pip environment.


Anaconda has it's own pip that needs to be installed in Anaconda.


Then, one just does pip install python-leventsheim.


Getting the path set in windoze is annoying, and needs to be set manually.

In *nix, one just sources an activation script and the path is modified.




Data Scientist
W2O Group
60 Francisco Street, San Francisco, CA 94133
cell 415.871.1909 | work 415.658.9738?

________________________________

**Comment by josegonzalez** [comment]
Cool, closing this out then, good to hear everything works now.

**Comment by askarbayev** [comment]
Hi there,
Even though I have installed python-Levenshtein, and it is in my module list, the error is still showing up which is "Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning".

**Comment by josegonzalez** [comment]
If you cannot run `from Levenshtein import *`, then you do not have python-Levenshtein setup in your python environment.
