### ISSUE TITLE
When using process and extractOne - check for exact matches

### ISSUE THREAD

**Issue by kraenhansen** [seatgeek/fuzzywuzzy#76]
If the limit argument for process.exact is 1 it might make sense to check for an exact match of query in choices before attempting fuzzy.

https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/process.py#L90

**Comment by josegonzalez** [comment]
Do you have a PR for this?

**Comment by acslater00** [comment]
I think this request is at-odds with the idea of passing a user defined scorer; we can't really guarantee that string equality, however we would define it, would actually represent the best match for any arbitrary scoring method (even though it seems like it should). So I think if this optimization is required it should be added in application code.
