### ISSUE TITLE
ImportError: cannot import name fuzz

### ISSUE THREAD

**Issue by harishvc** [seatgeek/fuzzywuzzy#78]
Below is more information.
``` 
$> sudo pip install fuzzywuzzy   #works, no error

$> vi mytest.py
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

$>python mytest.py
...
ImportError: cannot import name fuzz
```

**Comment by josegonzalez** [comment]
What environment are you running fuzzywuzzy under?

**Comment by harishvc** [comment]
Ubuntu (Linux). Thanks again for getting back.

**Comment by josegonzalez** [comment]
System python? What version of Ubuntu? Python version? I'll test in a VM.

**Comment by andrewtong** [comment]
I'm having a similar issue but with the Levinshtein module where I am unable to import the _levinshtein folders.  For reference I am using PyDev with Python 3.0, but I think its mainly an issue with being able to recognize the c file.

**Comment by harishvc** [comment]
@josegonzalez Python 2.7.6 & Ubuntu 14.04.1 LTS

**Comment by ecamaj** [comment]
same here... python 3.4, MacOS, installed from git repository, cannot import:

from fuzzywuzzy import fuzz
fuzz.ratio("this is a test", "this is a test!")
--- ImportError: cannot import name 'fuzz'

From Terminal works...?!

Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  5 2014, 20:42:22) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
>>> from fuzzywuzzy import fuzz
>>> fuzz.ratio("this is a test", "this is a test!")
97

**Comment by josegonzalez** [comment]
@ecamaj what do you mean you can't import it?

**Comment by ecamaj** [comment]
@josengonzalez I gave you exact output from Python: "ImportError: cannot import name 'fuzz'"

**Comment by ecamaj** [comment]
@josegonzalez I gave you exact output from Python: "ImportError: cannot import name 'fuzz'"

**Comment by kevin-brown** [comment]
Does anyone has a full traceback that they can provide for this issue?

It's probably a circular import somewhere.

**Comment by josegonzalez** [comment]
@ecamaj what python are you using vs the one in the terminal?

**Comment by ecamaj** [comment]
ok, forget it, this reminded me that sometimes I can be stupid. :)
named my test file fuzzywuzzy.py, didn't think about it, and on import he tried to import itself. :+1: 
Everything cool. :)
