### ISSUE TITLE
Unicode & token_sort_ratio

### ISSUE THREAD

**Issue by ffeast** [seatgeek/fuzzywuzzy#82]
Hi

What's wrong with this code snippet?

<pre><code>In [1]: from fuzzywuzzy import fuzz

In [2]: fuzz.token_sort_ratio(u"ааа ббб ввв", u"ббб ааа ввв")
Out[2]: 0

In [3]: fuzz.token_sort_ratio(u"aaa bbb ccc", u"bbb aaa ccc")
Out[3]: 100</code></pre>

$ python -V
Python 2.7.6

**Comment by ffeast** [comment]
Ok, got it.
There's an additional parameter force_ascii for my case.
Closing

**Comment by asanakoy** [comment]
There should be a mentioning of the parameter `force_ascii ` in the documentation. This is very bug prone. I got in this trap too.

**Comment by josegonzalez** [comment]
@asanakoy Can you add that to our documentation? Should be relatively quick. I would add it, but I don't know what contexts it is useful for and when it isn't.
