### ISSUE TITLE
Why is there a StringProcessor class?

### ISSUE THREAD

**Issue by SuperFluffy** [seatgeek/fuzzywuzzy#86]
Reading the source code, I was confused as to why there is a `StringProcessor` class defined in `string_processing.py`?  You never initialize it, and it contains only static methods; in fact, even the `replace_non_letters_non_numbers_with_whitespace()` can be made static by using the `@staticmethod` decorator. It appears like it is used entirely as a namespace.

Is there some extra reasoning behind this design that I missed? Or could the same thing be achieved  by just making all static methods free functions in a module?

EDIT: There is an [answer on Stackoverflow](http://stackoverflow.com/a/18262662/1889530) discussing functions which do not have a shared state.

**Comment by medecau** [comment]
A lot of things in fuzzywuzzy are tied to Seatgeek internals and don't seem to make much sense outside of it.

e.g.: defaulting to use asciidammit or throwing a warning when the levenshtein module is not found.

---

*can be closed*
