### ISSUE TITLE
Lost the ability of processing unicode choices

### ISSUE THREAD

**Issue by hylepo** [seatgeek/fuzzywuzzy#89]
Regarding of process.extract, when we call scorer, which is fuzz.WRatio actually, the exact locations are [process.py#L104](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/process.py#L104) and [process.py#L110](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/process.py#L110), we leave the third argument force_ascii to default value which is True according to [fuzz.py#L236](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/fuzz.py#L236) thus we can not process Unicode choices.

Solution:
1. provide one new parameter for process.extract at [process.py#L33](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/process.py#L33), means change
    `def extract(query, choices, processor=None, scorer=None, limit=5):`
to
    `def extract(query, choices, processor=None, scorer=None, limit=5, force_ascii=True):`
2. take the argument for fuzz.WRatio, means change [process.py#L104](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/process.py#L104) and [process.py#L110](https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/process.py#L110) from
     `score = scorer(query, processed)`
to
     `score = scorer(query, processed, force_ascii)`

**Comment by josegonzalez** [comment]
Mind providing a pr?

**Comment by hylepo** [comment]
Would you mind to check it here [Comparison](https://github.com/seatgeek/fuzzywuzzy/compare/master...hylepo:master)

**Comment by josegonzalez** [comment]
Looks good, can you make a PR including a test so we don't break this functionality in the future?

**Comment by josegonzalez** [comment]
Closing as there is a pr open.
