### ISSUE TITLE
fuzz.ratio(None,None) creates exception

### ISSUE THREAD

**Issue by timrichardson** [seatgeek/fuzzywuzzy#94]
Would it be possible for ratio to handle inputs of None as an empty string to avoid an exception?

**Comment by josegonzalez** [comment]
Just curious, why are you passing in a known bad value of `None` to the methods?

**Comment by timrichardson** [comment]
Databases rows  can return Null which is legal value and usually mapped to None. I would prefer to skip the validation and let fuzz.ratio treat it as an empty string, if that makes sense.

**Comment by josegonzalez** [comment]
Mind making a pr with corresponding tests?

**Comment by josegonzalez** [comment]
Closed by #110.
