### ISSUE TITLE
An advice

### ISSUE THREAD

**Issue by MacHu-GWU** [seatgeek/fuzzywuzzy#97]
Change:

```
from fuzzywuzzy.string_processing import StringProcessor

=>

from .string_processing import StringProcessor
```

in ``util.py`` is better

**Comment by josegonzalez** [comment]
Why is that better? Seems less straightforward to me.

**Comment by MacHu-GWU** [comment]
For example, if you move the whole package folder to another package folder as an subpackage

something/fuzzywuzzy/__init__.py

if you use ``from fuzzywuzzy.string_processing import StringProcessor``, it may not working. but if you use ``from .string_processing import StringProcessor``, then user can use fuzzywuzzy as ``from something.fuzzywuzzy import process`` without changing any of the source code.

**Comment by josegonzalez** [comment]
Sounds like if you are modifying the package anywyas, you can change the imports.

Closing since that is not the preferred way to install fuzzywuzzy and we won't be supporting it.
